name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  pr-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Download files from the current repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: universal-login

      - name: Build Universal Login
        run: make build
